### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by andilem** [alfredbaudisch/GodotDynamicInventorySystem#1]
I don't understand the license. It seems to be Apache 2.0, but you want the first line to be
```Copyright 2022 Alfred Reinold Baudisch (alfredbaudisch, pardall)```
I cannot see how this fits together at all. Please clarify.

**Comment by alfredbaudisch** [comment]
Apache 2.0 requires the inclusion of Copyright, Notice and the License itself: https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

**Comment by alfredbaudisch** [comment]
![image](https://user-images.githubusercontent.com/248383/166007434-5e24da13-4f59-40cb-87b1-985304fa6ac5.png)

**Comment by alfredbaudisch** [comment]
@andilem btw, if you still have questions, you can check this paragraph from the license itself - it talks about the inclusion of the Notice: https://github.com/alfredbaudisch/GodotDynamicInventorySystem/blob/master/LICENSE#L180

Anyway, Apache 2.0 is very flexible, you can do anything (commercially or not), as long as the Notice and Copyright is added to your project too.
