### ISSUE TITLE
Godot 4 support

### ISSUE THREAD

**Issue by Alvarden15** [alfredbaudisch/GodotDynamicInventorySystem#2]
Since the Godot 4 stable release is now out, when will the Godot 4 version come out? Just curious.

**Comment by alfredbaudisch** [comment]
Hey, I started remodeling the inventory course to Godot 4 and then the inventory project itself will come along (the code will be updated before the full course, since I need the updated code in order to update the content). But no ETA.

**Comment by Alvarden15** [comment]
Ok, thanks for the info!
BTW: it was a good idea to take inspiration from BOTW (in my opinion, at least).

**Comment by alfredbaudisch** [comment]
Thanks!

**Comment by Alvarden15** [comment]
Aaaand now that TOTK has been released, do you want to keep the BOTW layout or change it to TOTK's new layout? I ask that due to the many QoL changes made compared to BOTW's inventory system.

Thank you for your time.

**Comment by Bejasc** [comment]
hey @alfredbaudisch - any update on progress for Godot 4?

**Comment by alfredbaudisch** [comment]
You can follow the migration to Godot 4 here: #4

**Comment by alfredbaudisch** [comment]
Migrated to Godot 4. Code in the master branch.
